### ISSUE TITLE
Readme change social media icons

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/security_bear#61]
Please change the social media icons to be the same as the one at the bottom of this readme

https://github.com/CyBear-Jinni/cbj_app/blob/dev/README.md

**Comment by AloyBranCheung** [comment]
i'd like to do this pls

**Comment by sutirthverma** [comment]
Hey I can work on this issue, can you please assign it to me?

**Comment by guyluz11** [comment]
Pr got merged 

Thanks
