### ISSUE TITLE
Readme dart ci bage is icorrect

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/security_bear#64]
Readme dart ci bage is incorrect

Currently it comes from CBJ_Smart-Device repo
`[![dart CI](https://github.com/CyBear-Jinni/CBJ_Smart-Device/workflows/Dart%20CI/badge.svg)`

It should come from security_bear repo
`[[![dart CI](https://github.com/CyBear-Jinni/security_bear/workflows/Dart%20CI/badge.svg`

**Comment by ShrinathPawar** [comment]
Will you assign this issue to me?

**Comment by guyluz11** [comment]
Sure

**Comment by ShrinathPawar** [comment]
@guyluz11 You mean we have to change `[![dart CI](https://github.com/CyBear-Jinni/CBJ_Smart-Device/workflows/Dart%20CI/badge.svg)` To ` [![dart CI](https://github.com/CyBear-Jinni/security_bear/workflows/Dart%20CI/badge.svg)] `

**Comment by ShrinathPawar** [comment]
But both working in same way, is there any difference between it? Should i make PR ?
I have made above changes...

**Comment by guyluz11** [comment]
> @guyluz11 You mean we have to change `[![dart CI](https://github.com/CyBear-Jinni/CBJ_Smart-Device/workflows/Dart%20CI/badge.svg)` To `[![dart CI](https://github.com/CyBear-Jinni/security_bear/workflows/Dart%20CI/badge.svg)]`

The difference is `CBJ_Smart-Device` to `security_bear` not the extra brackets in the end

The difference is that it points to the wrong repo, so if the agitations will fail here it will show it pass as it points to the one that in the other repo

**Comment by ShrinathPawar** [comment]
@guyluz11 i know.... Yes.

**Comment by guyluz11** [comment]
Pr marged, will close now
