### ISSUE TITLE
YouTube logo in readme is not in the correct line 

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/security_bear#73]
The YouTube logo in readme file (dev branch) suppose to be in a new line of its own

![image](https://user-images.githubusercontent.com/9304740/194720902-51266654-83bd-4c47-bdc1-f2296ecaa9cf.png)

**Comment by syedzubeen** [comment]
@guyluz11 Can you assign me this.

**Comment by guyluz11** [comment]
@syedzubeen just open a PR, no need to be assigned ;)

**Comment by guyluz11** [comment]
Got merged

Thanks
