### ISSUE TITLE
Updated tag image in readme file

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/security_bear#9]
Please Update the "Open source" tag which is low quality image to this one

<img src="https://badges.frapsoft.com/os/v1/open-source-200x33.png?v=103" height="20">

`https://badges.frapsoft.com/os/v1/open-source-200x33.png?v=103`

**Comment by gitrahulgit** [comment]
I want to work on it

**Comment by guyluz11** [comment]
@gitrahulgit  Sure

**Comment by gitrahulgit** [comment]
Do you have any other repos for hacktober?
I'd like to contribute.

**Comment by guyluz11** [comment]
All here: https://github.com/CyBear-Jinni

If you want easy issue you can take a look at this one https://github.com/CyBear-Jinni/CBJ_Site/issues/5

**Comment by guyluz11** [comment]
Hard one with C++ and Linux knowledge 
https://github.com/CyBear-Jinni/CBJ_Smart-Device/issues/74

**Comment by ChancellorCeti** [comment]
I saw someone post a link to this issue recently, so if it is still not done, could you assign it to me?
Thanks

**Comment by guyluz11** [comment]
Ok @ChancellorCeti

**Comment by sakshi025** [comment]
I also want to work on this issue . can u please assign this to me @guyluz11

**Comment by guyluz11** [comment]
@sakshi025  It is already assing to someone else

**Comment by M-Rahul1** [comment]
I would like to contribute , if its incomplete assign me @guyluz11

**Comment by guyluz11** [comment]
Hi @ChancellorCeti  I am removing you from Assignees but your pr will still be merged if it will be accepted

Thanks

**Comment by guyluz11** [comment]
Pr got merged thanks
